// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mayngtwnrjbnsprrdwut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1heW5ndHducmpibnNwcnJkd3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTUyNzUsImV4cCI6MjA3Mzk5MTI3NX0.-UNFzUZCSICVYLSe6iFAHi5lSDg4gzbbAn5JWzy5-cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});